# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaf53d655c8632b48779cab16ec8cc2ffeb73857165eaf4dd0a6b82be04aac8d9aef092a4e792f9c69269a5e14a403f712e80bdabafaf57e10b8bede885b0575

test:
  secret_key_base: a530bd92ad37579920047f4c366bc22a537041261103761f31f16b47c102dec12a01fb43f7b184867f0e852c277e67225ebb2fe316a7871c50d6ca0527790b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
